PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX dctypes: <http://purl.org/dc/dcmitype/>
PREFIX dcterms: <http://purl.org/dc/terms/>
# Write a SPARQL query to display in Blazegraph:
#       Label and date of the first two Dante’s texts in chronological order
#       Family names of all people without duplicates
#       Label and date of all Dante’s texts created after 1310

# IRI and label of all people
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
SELECT ?iri ?label
WHERE { 
    ?iri rdf:type foaf:Person   .
    ?iri rdfs:label ?label .
    }

# Given name of all people with family name “Alighieri”
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
SELECT ?givenName 
WHERE {
    ?iri rdf:type foaf:Person   ;
        foaf:familyName "Alighieri" ;
        foaf:givenName  ?givenName  .
}

# IRI and label of all Dante’s texts in alphabetical order
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX dcterms:  <http://purl.org/dc/terms/>   
PREFIX dctypes: <http://purl.org/dc/dcmitype/>
PREFIX wd:<http://www.wikidata.org/entity/>
SELECT ?iri ?label
WHERE {
    ?iri rdf:type dctypes:Text  ;
         dcterms:creator wd:Q1067	;
         rdfs:label   ?label  .
}
ORDER BY ?label 


